# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RawPickGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 734)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 220))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.PickNumber = QtWidgets.QLCDNumber(self.groupBox_2)
        self.PickNumber.setMaximumSize(QtCore.QSize(16777215, 50))
        self.PickNumber.setObjectName("PickNumber")
        self.verticalLayout_5.addWidget(self.PickNumber)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_5.addWidget(self.checkBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.FrequencySpin = QtWidgets.QSpinBox(self.groupBox_3)
        self.FrequencySpin.setMaximum(1000)
        self.FrequencySpin.setObjectName("FrequencySpin")
        self.verticalLayout_6.addWidget(self.FrequencySpin)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setAutoFillBackground(False)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout_5.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout_5.addWidget(self.radioButton_2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.minSpinner = QtWidgets.QSpinBox(self.groupBox_4)
        self.minSpinner.setMinimum(-999999)
        self.minSpinner.setMaximum(999999)
        self.minSpinner.setObjectName("minSpinner")
        self.verticalLayout_7.addWidget(self.minSpinner)
        self.maxSpinner = QtWidgets.QSpinBox(self.groupBox_4)
        self.maxSpinner.setMinimum(-999999)
        self.maxSpinner.setMaximum(999999)
        self.maxSpinner.setObjectName("maxSpinner")
        self.verticalLayout_7.addWidget(self.maxSpinner)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.ColorSelector = QtWidgets.QComboBox(self.groupBox)
        self.ColorSelector.setObjectName("ColorSelector")
        self.ColorSelector.addItem("")
        self.ColorSelector.addItem("")
        self.ColorSelector.addItem("")
        self.ColorSelector.addItem("")
        self.verticalLayout_4.addWidget(self.ColorSelector)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FigCanvasWidget = MplFigCanvasWidget(self.centralwidget)
        self.FigCanvasWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.FigCanvasWidget.setObjectName("FigCanvasWidget")
        self.verticalLayout_2.addWidget(self.FigCanvasWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave_mat = QtWidgets.QMenu(self.menuFile)
        self.menuSave_mat.setObjectName("menuSave_mat")
        self.menuSave_figure = QtWidgets.QMenu(self.menuFile)
        self.menuSave_figure.setObjectName("menuSave_figure")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuPick = QtWidgets.QMenu(self.menubar)
        self.menuPick.setObjectName("menuPick")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSave_in_place = QtWidgets.QAction(MainWindow)
        self.actionSave_in_place.setObjectName("actionSave_in_place")
        self.actionSave_pick = QtWidgets.QAction(MainWindow)
        self.actionSave_pick.setObjectName("actionSave_pick")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_as_png = QtWidgets.QAction(MainWindow)
        self.actionSave_as_png.setObjectName("actionSave_as_png")
        self.actionColor_limits = QtWidgets.QAction(MainWindow)
        self.actionColor_limits.setObjectName("actionColor_limits")
        self.actionColor_map = QtWidgets.QAction(MainWindow)
        self.actionColor_map.setObjectName("actionColor_map")
        self.actionNext = QtWidgets.QAction(MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        self.actionPrevious.setObjectName("actionPrevious")
        self.menuSave_mat.addAction(self.actionSave_in_place)
        self.menuSave_mat.addAction(self.actionSave_pick)
        self.menuSave_mat.addAction(self.actionSave_as)
        self.menuSave_figure.addAction(self.actionSave_as_png)
        self.menuFile.addAction(self.menuSave_mat.menuAction())
        self.menuFile.addAction(self.menuSave_figure.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuView.addAction(self.actionColor_limits)
        self.menuView.addAction(self.actionColor_map)
        self.menuPick.addAction(self.actionNext)
        self.menuPick.addAction(self.actionPrevious)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuPick.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PickGUI"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Pick Options"))
        self.checkBox.setText(_translate("MainWindow", "Autopick"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Frequency"))
        self.radioButton.setText(_translate("MainWindow", "BWB"))
        self.radioButton_2.setText(_translate("MainWindow", "WBW"))
        self.groupBox.setTitle(_translate("MainWindow", "View Options"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Color limits"))
        self.ColorSelector.setItemText(0, _translate("MainWindow", "Gray"))
        self.ColorSelector.setItemText(1, _translate("MainWindow", "Viridis"))
        self.ColorSelector.setItemText(2, _translate("MainWindow", "BWR"))
        self.ColorSelector.setItemText(3, _translate("MainWindow", "Magma"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSave_mat.setTitle(_translate("MainWindow", "Save .mat"))
        self.menuSave_figure.setTitle(_translate("MainWindow", "Save figure"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuPick.setTitle(_translate("MainWindow", "Pick"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionSave_in_place.setText(_translate("MainWindow", "Save in place"))
        self.actionSave_pick.setText(_translate("MainWindow", "Save _pick"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as_png.setText(_translate("MainWindow", "Save png"))
        self.actionColor_limits.setText(_translate("MainWindow", "Color limits"))
        self.actionColor_map.setText(_translate("MainWindow", "Color map"))
        self.actionNext.setText(_translate("MainWindow", "Next"))
        self.actionPrevious.setText(_translate("MainWindow", "Previous"))

from ..mplfigcanvaswidget import MplFigCanvasWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

