# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RawPickGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.modeButton = QtWidgets.QPushButton(self.centralwidget)
        self.modeButton.setMaximumSize(QtCore.QSize(161, 32))
        self.modeButton.setObjectName("modeButton")
        self.verticalLayout_3.addWidget(self.modeButton)

        self.newpickButton = QtWidgets.QPushButton(self.centralwidget)
        self.newpickButton.setMaximumSize(QtCore.QSize(161, 32))
        self.newpickButton.setObjectName("newpickButton")
        self.verticalLayout_3.addWidget(self.newpickButton)

        self.autoButton = QtWidgets.QPushButton(self.centralwidget)
        self.autoButton.setMaximumSize(QtCore.QSize(161, 32))
        self.autoButton.setObjectName("autoButton")
        self.verticalLayout_3.addWidget(self.autoButton)

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(161, 250))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pickNumberBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.pickNumberBox.setGeometry(QtCore.QRect(7, 20, 100, 24))
        self.pickNumberBox.setMaximumSize(QtCore.QSize(100, 40))
        self.pickNumberBox.setMaximum(1000)
        self.pickNumberBox.setObjectName("pickNumberBox")
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.FrequencySpin = QtWidgets.QSpinBox(self.groupBox_3)
        self.FrequencySpin.setMaximum(1000)
        self.FrequencySpin.setObjectName("FrequencySpin")
        self.verticalLayout_6.addWidget(self.FrequencySpin)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.bwb_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.bwb_radio.setAutoFillBackground(False)
        self.bwb_radio.setChecked(True)
        self.bwb_radio.setObjectName("bwb_radio")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.bwb_radio)
        self.verticalLayout_5.addWidget(self.bwb_radio)
        self.wbw_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.wbw_radio.setObjectName("wbw_radio")
        self.buttonGroup.addButton(self.wbw_radio)
        self.verticalLayout_5.addWidget(self.wbw_radio)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(161, 200))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.minSpinner = QtWidgets.QSpinBox(self.groupBox_4)
        self.minSpinner.setMinimum(-999999)
        self.minSpinner.setMaximum(999999)
        self.minSpinner.setObjectName("minSpinner")
        self.verticalLayout_7.addWidget(self.minSpinner)
        self.maxSpinner = QtWidgets.QSpinBox(self.groupBox_4)
        self.maxSpinner.setMinimum(-999999)
        self.maxSpinner.setMaximum(999999)
        self.maxSpinner.setObjectName("maxSpinner")
        self.verticalLayout_7.addWidget(self.maxSpinner)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.ColorSelector = QtWidgets.QComboBox(self.groupBox)
        self.ColorSelector.setObjectName("ColorSelector")
        self.ColorSelector.addItem("")
        self.ColorSelector.addItem("")
        self.ColorSelector.addItem("")
        self.ColorSelector.addItem("")
        self.ColorSelector.addItem("")
        self.ColorSelector.addItem("")
        self.verticalLayout_4.addWidget(self.ColorSelector)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.progressLabel = QtWidgets.QLabel(self.centralwidget)
        self.progressLabel.setMaximumSize(QtCore.QSize(161, 16777215))
        self.progressLabel.setText("")
        self.progressLabel.setObjectName("progressLabel")
        self.verticalLayout_3.addWidget(self.progressLabel)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(161, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FigCanvasWidget = MplFigCanvasWidget(self.centralwidget)
        self.FigCanvasWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.FigCanvasWidget.setObjectName("FigCanvasWidget")
        self.verticalLayout_2.addWidget(self.FigCanvasWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave_mat = QtWidgets.QMenu(self.menuFile)
        self.menuSave_mat.setObjectName("menuSave_mat")
        self.menuSave_figure = QtWidgets.QMenu(self.menuFile)
        self.menuSave_figure.setObjectName("menuSave_figure")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuPick = QtWidgets.QMenu(self.menubar)
        self.menuPick.setObjectName("menuPick")
        self.menuExport = QtWidgets.QMenu(self.menuPick)
        self.menuExport.setObjectName("menuExport")
        self.menuProcess = QtWidgets.QMenu(self.menubar)
        self.menuProcess.setObjectName("menuProcess")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setProperty("shortcutVisibleInContextMenu", False)
        self.actionClose.setObjectName("actionClose")
        self.actionSave_in_place = QtWidgets.QAction(MainWindow)
        self.actionSave_in_place.setObjectName("actionSave_in_place")
        self.actionSave_pick = QtWidgets.QAction(MainWindow)
        self.actionSave_pick.setProperty("shortcutVisibleInContextMenu", False)
        self.actionSave_pick.setObjectName("actionSave_pick")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setProperty("shortcutVisibleInContextMenu", False)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_as_png = QtWidgets.QAction(MainWindow)
        self.actionSave_as_png.setObjectName("actionSave_as_png")
        self.actionColor_limits = QtWidgets.QAction(MainWindow)
        self.actionColor_limits.setObjectName("actionColor_limits")
        self.actionColor_map = QtWidgets.QAction(MainWindow)
        self.actionColor_map.setObjectName("actionColor_map")
        self.actionNext = QtWidgets.QAction(MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionVertical_band_pass = QtWidgets.QAction(MainWindow)
        self.actionVertical_band_pass.setObjectName("actionVertical_band_pass")
        self.actionAdaptive_Horizontal_filter = QtWidgets.QAction(MainWindow)
        self.actionAdaptive_Horizontal_filter.setObjectName("actionAdaptive_Horizontal_filter")
        self.actionCrop = QtWidgets.QAction(MainWindow)
        self.actionCrop.setObjectName("actionCrop")
        self.actionHcrop = QtWidgets.QAction(MainWindow)
        self.actionHcrop.setObjectName("actionHcrop")
        self.actionReverse = QtWidgets.QAction(MainWindow)
        self.actionReverse.setObjectName("actionReverse")
        self.actionLoad_crossprofile = QtWidgets.QAction(MainWindow)
        self.actionLoad_crossprofile.setObjectName("actionLoad_crossprofile")
        self.actionshp = QtWidgets.QAction(MainWindow)
        self.actionshp.setObjectName("actionshp")
        self.actioncsv = QtWidgets.QAction(MainWindow)
        self.actioncsv.setObjectName("actioncsv")
        self.actionFlatten_layer = QtWidgets.QAction(MainWindow)
        self.actionFlatten_layer.setObjectName("actionFlatten_layer")
        self.actionSwitch_data_matrix = QtWidgets.QAction(MainWindow)
        self.actionSwitch_data_matrix.setObjectName("actionSwitch_data_matrix")
        self.menuSave_mat.addAction(self.actionSave_pick)
        self.menuSave_mat.addAction(self.actionSave_as)
        self.menuSave_figure.addAction(self.actionSave_as_png)
        self.menuFile.addAction(self.menuSave_mat.menuAction())
        self.menuFile.addAction(self.menuSave_figure.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuView.addAction(self.actionFlatten_layer)
        self.menuView.addAction(self.actionSwitch_data_matrix)
        self.menuExport.addAction(self.actionshp)
        self.menuExport.addAction(self.actioncsv)
        self.menuPick.addAction(self.actionNext)
        self.menuPick.addAction(self.actionPrevious)
        self.menuPick.addSeparator()
        self.menuPick.addAction(self.menuExport.menuAction())
        self.menuPick.addSeparator()
        self.menuPick.addAction(self.actionLoad_crossprofile)
        self.menuProcess.addAction(self.actionVertical_band_pass)
        self.menuProcess.addAction(self.actionAdaptive_Horizontal_filter)
        self.menuProcess.addAction(self.actionCrop)
        self.menuProcess.addAction(self.actionHcrop)
        self.menuProcess.addAction(self.actionReverse)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuPick.menuAction())
        self.menubar.addAction(self.menuProcess.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PickGUI"))
        self.modeButton.setText(_translate("MainWindow", "Select Mode"))
        self.newpickButton.setText(_translate("MainWindow", "New Pick"))
        self.autoButton.setText(_translate("MainWindow", "Manual"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Pick Options"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Pick Number"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Frequency"))
        self.bwb_radio.setText(_translate("MainWindow", "BWB"))
        self.wbw_radio.setText(_translate("MainWindow", "WBW"))
        self.groupBox.setTitle(_translate("MainWindow", "View Options"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Color limits"))
        self.ColorSelector.setCurrentText(_translate("MainWindow", "gray"))
        self.ColorSelector.setItemText(0, _translate("MainWindow", "gray"))
        self.ColorSelector.setItemText(1, _translate("MainWindow", "CEGSIC"))
        self.ColorSelector.setItemText(2, _translate("MainWindow", "viridis"))
        self.ColorSelector.setItemText(3, _translate("MainWindow", "bwr"))
        self.ColorSelector.setItemText(4, _translate("MainWindow", "magma"))
        self.ColorSelector.setItemText(5, _translate("MainWindow", "bone"))
        self.checkBox_2.setText(_translate("MainWindow", "Reverse colors"))

        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSave_mat.setTitle(_translate("MainWindow", "Save .mat"))
        self.menuSave_figure.setTitle(_translate("MainWindow", "Save figure"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuPick.setTitle(_translate("MainWindow", "Pick"))
        self.menuExport.setTitle(_translate("MainWindow", "Export..."))
        self.menuProcess.setTitle(_translate("MainWindow", "Process"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionSave_in_place.setText(_translate("MainWindow", "Save in place"))
        self.actionSave_pick.setText(_translate("MainWindow", "Save"))
        self.actionSave_pick.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionSave_as_png.setText(_translate("MainWindow", "Save png"))
        self.actionColor_limits.setText(_translate("MainWindow", "Color limits"))
        self.actionColor_map.setText(_translate("MainWindow", "Color map"))
        self.actionNext.setText(_translate("MainWindow", "Next"))
        self.actionPrevious.setText(_translate("MainWindow", "Previous"))
        self.actionVertical_band_pass.setText(_translate("MainWindow", "Vertical band pass..."))
        self.actionAdaptive_Horizontal_filter.setText(_translate("MainWindow", "Adaptive Horizontal filter..."))
        self.actionCrop.setText(_translate("MainWindow", "Crop..."))
        self.actionHcrop.setText(_translate("MainWindow", "Hcrop..."))
        self.actionReverse.setText(_translate("MainWindow", "Reverse"))
        self.actionLoad_crossprofile.setText(_translate("MainWindow", "Load crossprofile"))
        self.actionshp.setText(_translate("MainWindow", "shp..."))
        self.actioncsv.setText(_translate("MainWindow", "csv..."))
        self.actionFlatten_layer.setText(_translate("MainWindow", "Flatten layer"))
        self.actionSwitch_data_matrix.setText(_translate("MainWindow", "Switch data matrix"))
from .mplfigcanvaswidget import MplFigCanvasWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
